### ISSUE TITLE
/usr/include/cublas_api.h:77:27: fatal error: library_types.h: No such file or directory

### ISSUE THREAD

**Issue by yancie-yjr** [raoyongming/PointGLR#11]
Scanning dependencies of target pointnet2_ext
[ 20%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/utils/csrc/cuda_compile_generated_ball_query_gpu.cu.o
[ 40%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/utils/csrc/cuda_compile_generated_group_points_gpu.cu.o
[ 60%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/utils/csrc/cuda_compile_generated_interpolate_gpu.cu.o
[ 80%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/utils/csrc/cuda_compile_generated_sampling_gpu.cu.o
[100%] Generating ../utils/_ext/pointnet2/_pointnet2.so
In file included from /usr/include/cublas_v2.h:65:0,
                 from /home/hustget/miniconda2/envs/torch0.4/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:14,
                 from /home/hustget/miniconda2/envs/torch0.4/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4,
                 from _pointnet2.c:570:
/usr/include/cublas_api.h:77:27: fatal error: library_types.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/hustget/A42C33A02C336D04/yangjinrong/PointGLR/utils/build_ffi.py", line 56, in <module>
    build(args)
  File "/media/hustget/A42C33A02C336D04/yangjinrong/PointGLR/utils/build_ffi.py", line 44, in build
    ffi.build()
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/site-packages/cffi/api.py", line 727, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/site-packages/cffi/recompiler.py", line 1565, in recompile
    compiler_verbose, debug)
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/hustget/miniconda2/envs/torch0.4/lib/python3.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command 'gcc' failed with exit status 1
CMakeFiles/pointnet2_ext.dir/build.make:67: recipe for target '../utils/_ext/pointnet2/_pointnet2.so' failed
make[2]: *** [../utils/_ext/pointnet2/_pointnet2.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pointnet2_ext.dir/all' failed
make[1]: *** [CMakeFiles/pointnet2_ext.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by raoyongming** [comment]
It looks like a CUDA-related error. I think you should check whether the CUDA library is correctly installed and the `cuda/include` path can be found by the compiler. In my environment, the missing file `library_types.h` is in `/usr/local/cuda/include/`.
